export enum KeyCode {
  Tab = 'Tab',
  Space = 'Space',
  Escape = 'Escape',
  Delete = 'Delete',
  AltLeft = 'AltLeft',
  AltRight = 'AltRight',
  ShiftLeft = 'ShiftLeft',
  Backspace = 'Backspace',
  CommandLeft = 'MetaLeft',
  CtrlLeft = 'ControlLeft',
  ShiftRight = 'ShiftRight',
  CommandRight = 'MetaRight',
  CtrlRight = 'ControlRight',
  F1 = 'F1',
  F2 = 'F2',
  F3 = 'F3',
  F4 = 'F4',
  F5 = 'F5',
  F6 = 'F6',
  F7 = 'F7',
  F8 = 'F8',
  F9 = 'F9',
  F10 = 'F10',
  F11 = 'F11',
  F12 = 'F12',
  A = 'KeyA',
  B = 'KeyB',
  C = 'KeyC',
  D = 'KeyD',
  E = 'KeyE',
  F = 'KeyF',
  G = 'KeyG',
  H = 'KeyH',
  I = 'KeyI',
  J = 'KeyJ',
  K = 'KeyK',
  L = 'KeyL',
  M = 'KeyM',
  N = 'KeyN',
  O = 'KeyO',
  P = 'KeyP',
  Q = 'KeyQ',
  R = 'KeyR',
  S = 'KeyS',
  T = 'KeyT',
  U = 'KeyU',
  V = 'KeyV',
  W = 'KeyW',
  X = 'KeyX',
  Y = 'KeyY',
  Z = 'KeyZ',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  ArrowLeft = 'ArrowLeft',
  ArrowRight = 'ArrowRight',
}

export const KEYCODE_HOTKEY_MAP = {
  [KeyCode.Escape]: 'esc',
  [KeyCode.AltLeft]: 'alt',
  [KeyCode.AltRight]: 'alt',
  [KeyCode.ShiftLeft]: 'shift',
  [KeyCode.ShiftRight]: 'shift',
  [KeyCode.CtrlLeft]: 'ctrl',
  [KeyCode.CtrlRight]: 'ctrl',
  [KeyCode.CommandLeft]: 'meta',
  [KeyCode.CommandRight]: 'meta',
  [KeyCode.Space]: 'space',
  [KeyCode.Delete]: 'delete',
  [KeyCode.Backspace]: 'delete',
  [KeyCode.F1]: 'f1',
  [KeyCode.F2]: 'f2',
  [KeyCode.F3]: 'f3',
  [KeyCode.F4]: 'f4',
  [KeyCode.F5]: 'f5',
  [KeyCode.F6]: 'f6',
  [KeyCode.F7]: 'f7',
  [KeyCode.F8]: 'f8',
  [KeyCode.F9]: 'f9',
  [KeyCode.F10]: 'f10',
  [KeyCode.F11]: 'f11',
  [KeyCode.F12]: 'f12',
  [KeyCode.A]: 'a',
  [KeyCode.B]: 'b',
  [KeyCode.C]: 'c',
  [KeyCode.D]: 'd',
  [KeyCode.E]: 'e',
  [KeyCode.F]: 'f',
  [KeyCode.G]: 'g',
  [KeyCode.H]: 'h',
  [KeyCode.I]: 'i',
  [KeyCode.J]: 'j',
  [KeyCode.K]: 'k',
  [KeyCode.L]: 'l',
  [KeyCode.M]: 'm',
  [KeyCode.N]: 'n',
  [KeyCode.O]: 'o',
  [KeyCode.P]: 'p',
  [KeyCode.Q]: 'q',
  [KeyCode.R]: 'r',
  [KeyCode.S]: 's',
  [KeyCode.T]: 't',
  [KeyCode.U]: 'u',
  [KeyCode.V]: 'v',
  [KeyCode.W]: 'w',
  [KeyCode.X]: 'x',
  [KeyCode.Y]: 'y',
  [KeyCode.Z]: 'z',
  [KeyCode.ArrowUp]: 'arrowup',
  [KeyCode.ArrowDown]: 'arrowdown',
  [KeyCode.ArrowLeft]: 'arrowleft',
  [KeyCode.ArrowRight]: 'arrowright',
};

//内部不处理的快键键，也不给浏览器处理
export enum SpecialHandleKeyCodeStr {
  CtrlS = 'ctrl+s',
  CtrlY = 'ctrl+y',
  CtrlO = 'ctrl+o',
  Alt = 'alt',
}